services:
  backend:
    build:
      context: ./backend
    container_name: app_backend
    environment:
      JWT_SECRET: secret
      CORS_ORIGIN: http://localhost:5001
    networks:
      - app-tier
    ports:
      - 3000:3000
    volumes:
      - ./backend/db:/app/db
    command: backend

networks:
  app-tier:
